// Mocks generated by Mockito 5.4.6 from annotations
// in x_pro_delivery_app/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i17;

import 'package:dartz/dartz.dart' as _i4;
import 'package:http/http.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:pocketbase/pocketbase.dart' as _i6;
import 'package:shared_preferences/shared_preferences.dart' as _i18;
import 'package:x_pro_delivery_app/core/common/app/features/trip_ticket/trip/data/models/trip_models.dart'
    as _i3;
import 'package:x_pro_delivery_app/core/common/app/features/trip_ticket/trip/domain/entity/trip_entity.dart'
    as _i14;
import 'package:x_pro_delivery_app/core/common/app/features/users/auth/data/datasources/local_datasource/auth_local_data_source.dart'
    as _i10;
import 'package:x_pro_delivery_app/core/common/app/features/users/auth/data/datasources/remote_data_source/auth_remote_data_src.dart'
    as _i9;
import 'package:x_pro_delivery_app/core/common/app/features/users/auth/data/models/auth_models.dart'
    as _i2;
import 'package:x_pro_delivery_app/core/common/app/features/users/auth/domain/entity/users_entity.dart'
    as _i13;
import 'package:x_pro_delivery_app/core/common/app/features/users/auth/domain/repo/auth_repo.dart'
    as _i11;
import 'package:x_pro_delivery_app/core/common/app/provider/check_connectivity_provider.dart'
    as _i15;
import 'package:x_pro_delivery_app/core/errors/failures.dart' as _i12;
import 'package:x_pro_delivery_app/core/services/offline_sync_service.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocalUsersModel_0 extends _i1.SmartFake
    implements _i2.LocalUsersModel {
  _FakeLocalUsersModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTripModel_1 extends _i1.SmartFake implements _i3.TripModel {
  _FakeTripModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncResult_3 extends _i1.SmartFake implements _i5.SyncResult {
  _FakeSyncResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncStatus_4 extends _i1.SmartFake implements _i5.SyncStatus {
  _FakeSyncStatus_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthStore_5 extends _i1.SmartFake implements _i6.AuthStore {
  _FakeAuthStore_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionService_6 extends _i1.SmartFake
    implements _i6.CollectionService {
  _FakeCollectionService_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileService_7 extends _i1.SmartFake implements _i6.FileService {
  _FakeFileService_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeService_8 extends _i1.SmartFake
    implements _i6.RealtimeService {
  _FakeRealtimeService_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsService_9 extends _i1.SmartFake
    implements _i6.SettingsService {
  _FakeSettingsService_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogService_10 extends _i1.SmartFake implements _i6.LogService {
  _FakeLogService_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealthService_11 extends _i1.SmartFake implements _i6.HealthService {
  _FakeHealthService_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBackupService_12 extends _i1.SmartFake implements _i6.BackupService {
  _FakeBackupService_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCronService_13 extends _i1.SmartFake implements _i6.CronService {
  _FakeCronService_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_14 extends _i1.SmartFake implements _i7.Client {
  _FakeClient_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecordService_15 extends _i1.SmartFake implements _i6.RecordService {
  _FakeRecordService_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_16 extends _i1.SmartFake implements Uri {
  _FakeUri_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatchService_17 extends _i1.SmartFake implements _i6.BatchService {
  _FakeBatchService_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_18<T1> extends _i1.SmartFake implements _i8.Future<T1> {
  _FakeFuture_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSrc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSrc extends _i1.Mock implements _i9.AuthRemoteDataSrc {
  MockAuthRemoteDataSrc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.LocalUsersModel> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i8.Future<_i2.LocalUsersModel>.value(
              _FakeLocalUsersModel_0(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.LocalUsersModel>);

  @override
  _i8.Future<_i2.LocalUsersModel> refreshUserData() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUserData, []),
            returnValue: _i8.Future<_i2.LocalUsersModel>.value(
              _FakeLocalUsersModel_0(
                this,
                Invocation.method(#refreshUserData, []),
              ),
            ),
          )
          as _i8.Future<_i2.LocalUsersModel>);

  @override
  _i8.Future<_i2.LocalUsersModel> loadUser() =>
      (super.noSuchMethod(
            Invocation.method(#loadUser, []),
            returnValue: _i8.Future<_i2.LocalUsersModel>.value(
              _FakeLocalUsersModel_0(this, Invocation.method(#loadUser, [])),
            ),
          )
          as _i8.Future<_i2.LocalUsersModel>);

  @override
  _i8.Future<_i2.LocalUsersModel> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i8.Future<_i2.LocalUsersModel>.value(
              _FakeLocalUsersModel_0(
                this,
                Invocation.method(#getUserById, [userId]),
              ),
            ),
          )
          as _i8.Future<_i2.LocalUsersModel>);

  @override
  _i8.Future<_i3.TripModel> getUserTrip(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTrip, [userId]),
            returnValue: _i8.Future<_i3.TripModel>.value(
              _FakeTripModel_1(this, Invocation.method(#getUserTrip, [userId])),
            ),
          )
          as _i8.Future<_i3.TripModel>);

  @override
  _i8.Future<_i2.LocalUsersModel> syncUserData(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#syncUserData, [userId]),
            returnValue: _i8.Future<_i2.LocalUsersModel>.value(
              _FakeLocalUsersModel_0(
                this,
                Invocation.method(#syncUserData, [userId]),
              ),
            ),
          )
          as _i8.Future<_i2.LocalUsersModel>);

  @override
  _i8.Future<_i3.TripModel> syncUserTripData(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#syncUserTripData, [userId]),
            returnValue: _i8.Future<_i3.TripModel>.value(
              _FakeTripModel_1(
                this,
                Invocation.method(#syncUserTripData, [userId]),
              ),
            ),
          )
          as _i8.Future<_i3.TripModel>);
}

/// A class which mocks [AuthLocalDataSrc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSrc extends _i1.Mock implements _i10.AuthLocalDataSrc {
  MockAuthLocalDataSrc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.LocalUsersModel> getLocalUser() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalUser, []),
            returnValue: _i8.Future<_i2.LocalUsersModel>.value(
              _FakeLocalUsersModel_0(
                this,
                Invocation.method(#getLocalUser, []),
              ),
            ),
          )
          as _i8.Future<_i2.LocalUsersModel>);

  @override
  _i8.Future<_i2.LocalUsersModel> loadLocalUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#loadLocalUserById, [userId]),
            returnValue: _i8.Future<_i2.LocalUsersModel>.value(
              _FakeLocalUsersModel_0(
                this,
                Invocation.method(#loadLocalUserById, [userId]),
              ),
            ),
          )
          as _i8.Future<_i2.LocalUsersModel>);

  @override
  _i8.Future<void> saveUser(_i2.LocalUsersModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearUser, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> hasUser() =>
      (super.noSuchMethod(
            Invocation.method(#hasUser, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i3.TripModel> loadLocalUserTrip(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#loadLocalUserTrip, [userId]),
            returnValue: _i8.Future<_i3.TripModel>.value(
              _FakeTripModel_1(
                this,
                Invocation.method(#loadLocalUserTrip, [userId]),
              ),
            ),
          )
          as _i8.Future<_i3.TripModel>);

  @override
  _i8.Future<void> cacheUserData(_i2.LocalUsersModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserData, [user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> cacheUserTripData(_i3.TripModel? trip) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserTripData, [trip]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveUserTripByUserId(String? userId, _i3.TripModel? trip) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserTripByUserId, [userId, trip]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.TripModel> forceReloadLocalUserTrip(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#forceReloadLocalUserTrip, [userId]),
            returnValue: _i8.Future<_i3.TripModel>.value(
              _FakeTripModel_1(
                this,
                Invocation.method(#forceReloadLocalUserTrip, [userId]),
              ),
            ),
          )
          as _i8.Future<_i3.TripModel>);

  @override
  _i8.Future<_i2.LocalUsersModel> forceReloadLocalUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#forceReloadLocalUserById, [userId]),
            returnValue: _i8.Future<_i2.LocalUsersModel>.value(
              _FakeLocalUsersModel_0(
                this,
                Invocation.method(#forceReloadLocalUserById, [userId]),
              ),
            ),
          )
          as _i8.Future<_i2.LocalUsersModel>);
}

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i11.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>>.value(
                  _FakeEither_2<_i12.Failure, _i13.LocalUser>(
                    this,
                    Invocation.method(#signIn, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>>);

  @override
  _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>> refreshUserData() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUserData, []),
            returnValue:
                _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>>.value(
                  _FakeEither_2<_i12.Failure, _i13.LocalUser>(
                    this,
                    Invocation.method(#refreshUserData, []),
                  ),
                ),
          )
          as _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>>);

  @override
  _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>> getUserById(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue:
                _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>>.value(
                  _FakeEither_2<_i12.Failure, _i13.LocalUser>(
                    this,
                    Invocation.method(#getUserById, [userId]),
                  ),
                ),
          )
          as _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>>);

  @override
  _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>> loadLocalUserById(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadLocalUserById, [userId]),
            returnValue:
                _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>>.value(
                  _FakeEither_2<_i12.Failure, _i13.LocalUser>(
                    this,
                    Invocation.method(#loadLocalUserById, [userId]),
                  ),
                ),
          )
          as _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>>);

  @override
  _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>> loadLocalUserData() =>
      (super.noSuchMethod(
            Invocation.method(#loadLocalUserData, []),
            returnValue:
                _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>>.value(
                  _FakeEither_2<_i12.Failure, _i13.LocalUser>(
                    this,
                    Invocation.method(#loadLocalUserData, []),
                  ),
                ),
          )
          as _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>>);

  @override
  _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>> loadUser() =>
      (super.noSuchMethod(
            Invocation.method(#loadUser, []),
            returnValue:
                _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>>.value(
                  _FakeEither_2<_i12.Failure, _i13.LocalUser>(
                    this,
                    Invocation.method(#loadUser, []),
                  ),
                ),
          )
          as _i8.Future<_i4.Either<_i12.Failure, _i13.LocalUser>>);

  @override
  _i8.Future<_i4.Either<_i12.Failure, _i14.TripEntity>> getUserTrip(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTrip, [userId]),
            returnValue:
                _i8.Future<_i4.Either<_i12.Failure, _i14.TripEntity>>.value(
                  _FakeEither_2<_i12.Failure, _i14.TripEntity>(
                    this,
                    Invocation.method(#getUserTrip, [userId]),
                  ),
                ),
          )
          as _i8.Future<_i4.Either<_i12.Failure, _i14.TripEntity>>);

  @override
  _i8.Future<_i4.Either<_i12.Failure, _i14.TripEntity>> loadLocalUserTrip(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadLocalUserTrip, [userId]),
            returnValue:
                _i8.Future<_i4.Either<_i12.Failure, _i14.TripEntity>>.value(
                  _FakeEither_2<_i12.Failure, _i14.TripEntity>(
                    this,
                    Invocation.method(#loadLocalUserTrip, [userId]),
                  ),
                ),
          )
          as _i8.Future<_i4.Either<_i12.Failure, _i14.TripEntity>>);

  @override
  _i8.Future<_i4.Either<_i12.Failure, void>> syncUserData(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#syncUserData, [userId]),
            returnValue: _i8.Future<_i4.Either<_i12.Failure, void>>.value(
              _FakeEither_2<_i12.Failure, void>(
                this,
                Invocation.method(#syncUserData, [userId]),
              ),
            ),
          )
          as _i8.Future<_i4.Either<_i12.Failure, void>>);

  @override
  _i8.Future<_i4.Either<_i12.Failure, void>> syncUserTripData(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#syncUserTripData, [userId]),
            returnValue: _i8.Future<_i4.Either<_i12.Failure, void>>.value(
              _FakeEither_2<_i12.Failure, void>(
                this,
                Invocation.method(#syncUserTripData, [userId]),
              ),
            ),
          )
          as _i8.Future<_i4.Either<_i12.Failure, void>>);

  @override
  _i8.Future<_i4.Either<_i12.Failure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i8.Future<_i4.Either<_i12.Failure, void>>.value(
              _FakeEither_2<_i12.Failure, void>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i8.Future<_i4.Either<_i12.Failure, void>>);
}

/// A class which mocks [OfflineSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineSyncService extends _i1.Mock
    implements _i5.OfflineSyncService {
  MockOfflineSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> initialize(_i6.PocketBase? pocketBase) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [pocketBase]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> queueOperation(_i5.OfflineOperation? operation) =>
      (super.noSuchMethod(
            Invocation.method(#queueOperation, [operation]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.SyncResult> syncAll() =>
      (super.noSuchMethod(
            Invocation.method(#syncAll, []),
            returnValue: _i8.Future<_i5.SyncResult>.value(
              _FakeSyncResult_3(this, Invocation.method(#syncAll, [])),
            ),
          )
          as _i8.Future<_i5.SyncResult>);

  @override
  _i5.SyncStatus getCurrentStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentStatus, []),
            returnValue: _FakeSyncStatus_4(
              this,
              Invocation.method(#getCurrentStatus, []),
            ),
          )
          as _i5.SyncStatus);

  @override
  _i8.Future<void> clearQueue() =>
      (super.noSuchMethod(
            Invocation.method(#clearQueue, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearFailedOperations() =>
      (super.noSuchMethod(
            Invocation.method(#clearFailedOperations, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [ConnectivityProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityProvider extends _i1.Mock
    implements _i15.ConnectivityProvider {
  MockConnectivityProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get disposed =>
      (super.noSuchMethod(Invocation.getter(#disposed), returnValue: false)
          as bool);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  int get latency =>
      (super.noSuchMethod(Invocation.getter(#latency), returnValue: 0) as int);

  @override
  String get connectionType =>
      (super.noSuchMethod(
            Invocation.getter(#connectionType),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#connectionType),
            ),
          )
          as String);

  @override
  bool get isSyncing =>
      (super.noSuchMethod(Invocation.getter(#isSyncing), returnValue: false)
          as bool);

  @override
  List<String> get pendingSyncOperations =>
      (super.noSuchMethod(
            Invocation.getter(#pendingSyncOperations),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  set disposed(bool? _disposed) => super.noSuchMethod(
    Invocation.setter(#disposed, _disposed),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void addPendingSyncOperation(String? operation) => super.noSuchMethod(
    Invocation.method(#addPendingSyncOperation, [operation]),
    returnValueForMissingStub: null,
  );

  @override
  void removePendingSyncOperation(String? operation) => super.noSuchMethod(
    Invocation.method(#removePendingSyncOperation, [operation]),
    returnValueForMissingStub: null,
  );

  @override
  void setSyncStatus(bool? syncing) => super.noSuchMethod(
    Invocation.method(#setSyncStatus, [syncing]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i18.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i8.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [PocketBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPocketBase extends _i1.Mock implements _i6.PocketBase {
  MockPocketBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseURL =>
      (super.noSuchMethod(
            Invocation.getter(#baseURL),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#baseURL),
            ),
          )
          as String);

  @override
  String get lang =>
      (super.noSuchMethod(
            Invocation.getter(#lang),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#lang),
            ),
          )
          as String);

  @override
  _i6.AuthStore get authStore =>
      (super.noSuchMethod(
            Invocation.getter(#authStore),
            returnValue: _FakeAuthStore_5(this, Invocation.getter(#authStore)),
          )
          as _i6.AuthStore);

  @override
  _i6.CollectionService get collections =>
      (super.noSuchMethod(
            Invocation.getter(#collections),
            returnValue: _FakeCollectionService_6(
              this,
              Invocation.getter(#collections),
            ),
          )
          as _i6.CollectionService);

  @override
  _i6.FileService get files =>
      (super.noSuchMethod(
            Invocation.getter(#files),
            returnValue: _FakeFileService_7(this, Invocation.getter(#files)),
          )
          as _i6.FileService);

  @override
  _i6.RealtimeService get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeService_8(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i6.RealtimeService);

  @override
  _i6.SettingsService get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettingsService_9(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i6.SettingsService);

  @override
  _i6.LogService get logs =>
      (super.noSuchMethod(
            Invocation.getter(#logs),
            returnValue: _FakeLogService_10(this, Invocation.getter(#logs)),
          )
          as _i6.LogService);

  @override
  _i6.HealthService get health =>
      (super.noSuchMethod(
            Invocation.getter(#health),
            returnValue: _FakeHealthService_11(
              this,
              Invocation.getter(#health),
            ),
          )
          as _i6.HealthService);

  @override
  _i6.BackupService get backups =>
      (super.noSuchMethod(
            Invocation.getter(#backups),
            returnValue: _FakeBackupService_12(
              this,
              Invocation.getter(#backups),
            ),
          )
          as _i6.BackupService);

  @override
  _i6.CronService get crons =>
      (super.noSuchMethod(
            Invocation.getter(#crons),
            returnValue: _FakeCronService_13(this, Invocation.getter(#crons)),
          )
          as _i6.CronService);

  @override
  _i7.Client Function() get httpClientFactory =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientFactory),
            returnValue:
                () =>
                    _FakeClient_14(this, Invocation.getter(#httpClientFactory)),
          )
          as _i7.Client Function());

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i6.RecordService get admins =>
      (super.noSuchMethod(
            Invocation.getter(#admins),
            returnValue: _FakeRecordService_15(
              this,
              Invocation.getter(#admins),
            ),
          )
          as _i6.RecordService);

  @override
  set baseURL(String? _baseURL) => super.noSuchMethod(
    Invocation.setter(#baseURL, _baseURL),
    returnValueForMissingStub: null,
  );

  @override
  set lang(String? _lang) => super.noSuchMethod(
    Invocation.setter(#lang, _lang),
    returnValueForMissingStub: null,
  );

  @override
  set authStore(_i6.AuthStore? _authStore) => super.noSuchMethod(
    Invocation.setter(#authStore, _authStore),
    returnValueForMissingStub: null,
  );

  @override
  set collections(_i6.CollectionService? _collections) => super.noSuchMethod(
    Invocation.setter(#collections, _collections),
    returnValueForMissingStub: null,
  );

  @override
  set files(_i6.FileService? _files) => super.noSuchMethod(
    Invocation.setter(#files, _files),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i6.RealtimeService? _realtime) => super.noSuchMethod(
    Invocation.setter(#realtime, _realtime),
    returnValueForMissingStub: null,
  );

  @override
  set settings(_i6.SettingsService? _settings) => super.noSuchMethod(
    Invocation.setter(#settings, _settings),
    returnValueForMissingStub: null,
  );

  @override
  set logs(_i6.LogService? _logs) => super.noSuchMethod(
    Invocation.setter(#logs, _logs),
    returnValueForMissingStub: null,
  );

  @override
  set health(_i6.HealthService? _health) => super.noSuchMethod(
    Invocation.setter(#health, _health),
    returnValueForMissingStub: null,
  );

  @override
  set backups(_i6.BackupService? _backups) => super.noSuchMethod(
    Invocation.setter(#backups, _backups),
    returnValueForMissingStub: null,
  );

  @override
  set crons(_i6.CronService? _crons) => super.noSuchMethod(
    Invocation.setter(#crons, _crons),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientFactory(_i7.Client Function()? _httpClientFactory) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientFactory, _httpClientFactory),
        returnValueForMissingStub: null,
      );

  @override
  set baseUrl(String? v) => super.noSuchMethod(
    Invocation.setter(#baseUrl, v),
    returnValueForMissingStub: null,
  );

  @override
  _i6.RecordService collection(String? collectionIdOrName) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [collectionIdOrName]),
            returnValue: _FakeRecordService_15(
              this,
              Invocation.method(#collection, [collectionIdOrName]),
            ),
          )
          as _i6.RecordService);

  @override
  String filter(String? expr, [Map<String, dynamic>? query = const {}]) =>
      (super.noSuchMethod(
            Invocation.method(#filter, [expr, query]),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#filter, [expr, query]),
            ),
          )
          as String);

  @override
  Uri getFileUrl(
    _i6.RecordModel? record,
    String? filename, {
    String? thumb,
    String? token,
    Map<String, dynamic>? query = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFileUrl,
              [record, filename],
              {#thumb: thumb, #token: token, #query: query},
            ),
            returnValue: _FakeUri_16(
              this,
              Invocation.method(
                #getFileUrl,
                [record, filename],
                {#thumb: thumb, #token: token, #query: query},
              ),
            ),
          )
          as Uri);

  @override
  Uri buildUrl(
    String? path, [
    Map<String, dynamic>? queryParameters = const {},
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#buildUrl, [path, queryParameters]),
            returnValue: _FakeUri_16(
              this,
              Invocation.method(#buildUrl, [path, queryParameters]),
            ),
          )
          as Uri);

  @override
  Uri buildURL(
    String? path, [
    Map<String, dynamic>? queryParameters = const {},
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#buildURL, [path, queryParameters]),
            returnValue: _FakeUri_16(
              this,
              Invocation.method(#buildURL, [path, queryParameters]),
            ),
          )
          as Uri);

  @override
  _i6.BatchService createBatch() =>
      (super.noSuchMethod(
            Invocation.method(#createBatch, []),
            returnValue: _FakeBatchService_17(
              this,
              Invocation.method(#createBatch, []),
            ),
          )
          as _i6.BatchService);

  @override
  _i8.Future<T> send<T extends dynamic>(
    String? path, {
    String? method = 'GET',
    Map<String, String>? headers = const {},
    Map<String, dynamic>? query = const {},
    Map<String, dynamic>? body = const {},
    List<_i7.MultipartFile>? files = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #send,
              [path],
              {
                #method: method,
                #headers: headers,
                #query: query,
                #body: body,
                #files: files,
              },
            ),
            returnValue:
                _i16.ifNotNull(
                  _i16.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #send,
                      [path],
                      {
                        #method: method,
                        #headers: headers,
                        #query: query,
                        #body: body,
                        #files: files,
                      },
                    ),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_18<T>(
                  this,
                  Invocation.method(
                    #send,
                    [path],
                    {
                      #method: method,
                      #headers: headers,
                      #query: query,
                      #body: body,
                      #files: files,
                    },
                  ),
                ),
          )
          as _i8.Future<T>);
}
